app/trade/forms.py
# -*- coding: UTF-8 -*-

from flask.ext.wtf import Form
from wtforms import StringField,SubmitField,SelectField,BooleanField,TextAreaField,FloatField,IntegerField,DateTimeField
from wtforms.validators import Required,Email,EqualTo,Length
from ..models import User,Role,Post
from wtforms import ValidationError

class PostForm(Form):
    
    name=StringField(u'物品名称', validators=[Required(),Length(1, 128)])
    num=IntegerField(u'物品数量')
    price=FloatField(u'物品价格')
    tag=SelectField(u'物品类别', choices=[('0',u'生活用品'), ('1',u'数码科技'), ('2', u'服饰箱包'),('3', u'图书音像'), ('4',u'其它')])
    location=StringField(u'所在楼栋')
    buyTime=StringField(u'购买时间')
    quality=StringField(u'物品成色')
    mycontact=StringField(u'联系方式', validators=[Required(),Length(1,64)])
    body=TextAreaField(u'物品介绍')
    img=StringField(u'图片链接')
    submit=SubmitField(u'提交')


class CommentForm(Form):
    body=TextAreaField(u'评论', validators=[Required()])
    submit=SubmitField(u'提交')


class SearchForm(Form):
    querybody = StringField(u'查询内容',)
    submit = SubmitField(u'查询')


class deleteForm(Form):
    pid = IntegerField(u'帖子id', validators=[Required()])
    submit = SubmitField(u'删除')

app/trade/__init__.py
# -*- coding: UTF-8 -*-
from flask import Blueprint

trade=Blueprint('trade',__name__)
from . import errors,views

app/trade/views.py
# -*- coding: UTF-8 -*-
from flask import render_template,redirect,url_for,session,flash,request,current_app,request,jsonify
from ..decorators import admin_required,permission_required
from . import trade
from .. import db
from flask.ext.login import login_required,current_user
from ..models import Permission,User,Role,Post,Comment,getPrimaryKeyId
from forms import PostForm,CommentForm, SearchForm , deleteForm
from json import loads


@trade.route('/trade_list')
def trade_list():
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(
        page, per_page=current_app.config['JXNUGO_POSTS_PER_PAGE'],
        error_out=False)
    posts = pagination.items
    return render_template('trade/trade_list.html',posts=posts,pagination=pagination)


@trade.route('/trade_post',methods=['POST', 'GET'])
@login_required
def trade_post():
    form = PostForm()
    if form.validate_on_submit():
        recv = form.img.data
        s = loads(recv)
        l = []
        for x in s['photos']:
            temp = x['key']
            l.append(temp)
        photo = ":".join(l)
        post = Post(id=getPrimaryKeyId('isPost'), body=form.body.data, goodName=form.name.data, goodPrice=form.price.data,
                  goodNum=form.num.data, goodLocation=form.location.data, goodQuality=form.quality.data,
                  goodTag=form.tag.data, contact=form.mycontact.data, goodBuyTime=form.buyTime.data,  photos=photo, author_id=current_user.id)
        db.session.add(post)
        db.session.commit()
        flash(u'帖子发布成功')
        return redirect(url_for('trade.trade_list'))  # 感觉 返回列表会好一些
    return render_template('trade/trade_post.html', form=form)


@trade.route('/trade_detail/<goodId>', methods=['GET', 'POST'])
def trade_detail(goodId):
    post = Post.query.get_or_404(goodId)
    form = CommentForm()
    if form.validate_on_submit():
        if current_user.is_anonymous:
            flash(u'请登录后再尝试评论帖子')
            return redirect(url_for('auth.passport'))
        else:
            comment = Comment(body=form.body.data, post=post,
            author = current_user._get_current_object())
            db.session.add(comment)
            db.session.commit()
            flash(u'你的评论已提交.')
            return redirect(url_for('.trade_detail', goodId=post.id, page=-1))
    page = request.args.get('page', 1, type=int)
    if page == -1:
        page = (post.comments.count() - 1) // \
            current_app.config['JXNUGO_COMMENTS_PER_PAGE'] + 1
    pagination = post.comments.order_by(Comment.timestamp.asc()).paginate(
        page, per_page=current_app.config['JXNUGO_COMMENTS_PER_PAGE'],
        error_out=False)
    comments = pagination.items
    author = current_user._get_current_object()
    return render_template('trade/trade_detail.html', post=post, form=form,
                           comments=comments, pagination=pagination,user=author)


@trade.route('/collect/<pid>',methods=['GET'])
@login_required
def collect(pid):
    post = Post.query.filter_by(id=pid).first()
    if post is None:
        flash(u'该帖子不存在')
    if current_user.is_collecting(post):
        flash(u'已经收藏了这篇帖子,无需再次收藏')
        return redirect(url_for('.trade_detail',goodId=pid))
    current_user.collect(post)
    flash(u'收藏成功')
    return redirect(url_for('.trade_detail',goodId=pid))


@trade.route('/uncollect/<pid>', methods=['GET'])
@login_required
def uncollect(pid):
    post = Post.query.filter_by(id=pid).first()
    if post is None:
        flash(u'该帖子不存在')
    current_user.uncollect(post)
    flash(u'成功取消收藏')
    return redirect(url_for('.trade_detail',goodId=pid))


@trade.route('/moderate')
@login_required
@permission_required(Permission.MODERATE_COMMENTS)
def moderate():
    page = request.args.get('page',1,type=int)
    pagination = Comment.query.order_by(Comment.timestamp.desc()).paginate(
        page, per_page=current_app.config['JXNUGO_COMMENT_PER_PAGE'],
        error_out=False
    )
    comments = pagination.items
    return render_template('trade/moderate.html', comments=comments, pagination=pagination, page=page)


@trade.route('/moderate/enable/<int:id>')
@login_required
@permission_required(Permission.MODERATE_COMMENTS)
def moderate_enable(id):
    comment = Comment.query.get_or_404(id)
    comment.disabled = False
    db.session.add(comment)
    return redirect(url_for('.moderate',
                            page=request.args.get('page', 1, type=int)), )


@trade.route('/moderate/disable/<int:id>')
@login_required
@permission_required(Permission.MODERATE_COMMENTS)
def moderate_disable(id):
    comment = Comment.query.get_or_404(id)
    comment.disabled = True
    db.session.add(comment)
    return redirect(url_for('.moderate',
                            page=request.args.get('page', 1, type=int)), )


@trade.route('/query_post/<problem>')
def query_post(problem):
    queryname = problem
    print queryname
    if queryname == '':
        flash('请输入关键字后再进行查询操作')
        return redirect(url_for('.trade_list'))
    else:
        page = request.args.get('page', 1, type=int)
        pagination = Post.query.filter(Post.goodName.like('%'+queryname+'%')).paginate(
            page, per_page=current_app.config['JXNUGO_POSTS_PER_PAGE'],
            error_out=False
        )
    
        posts = pagination.items
        return render_template('trade/query_posts.html', posts=posts, pagination=pagination,problem=problem)


@trade.route('/post_category/<posttag>')
def post_category(posttag):
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.filter_by(goodTag=posttag).paginate(
        page, per_page=current_app.config['JXNUGO_POSTS_PER_PAGE'],
        error_out=False
    )
    posts = pagination.items
    return render_template('trade/trade_list.html', posts=posts, pagination=pagination)


@trade.route('/post_delete', methods=['GET', 'POST'])
@login_required
@admin_required
def post_delete():
    delete_postid = deleteForm()
    if delete_postid.validate_on_submit():
        pid = delete_postid.pid.data
        p = Post.query.filter_by(id=pid).first()
        if p is None:
            flash(u'该帖子不存在')
        else:
            comments = Comment.query.filter_by(post_id=p.id).all()  # 删除评论
            for comment in comments:
                db.session.delete(comment)
            all_user = User.query.all()     # 删除收藏的关系
            for user in all_user:
                if p in user.collectionPost.all():
                    user.collectionPost.remove(p)
                else:
                    pass
            db.session.delete(p)
            db.session.commit()
            flash(u'帖子及其评论删除成功')
    return render_template('trade/post_delete.html', form=delete_postid)


@trade.route('/delete_self_post/<int:pid>')
@login_required
def delete_self_post(pid):
    p = Post.query.filter_by(id=pid).first()
    if p is None:
        flash(u'该帖子不存在')
    else:
        comments = Comment.query.filter_by(post_id=p.id).all()  # 删除评论
        for comment in comments:
            db.session.delete(comment)
        all_user = User.query.all()     # 删除收藏的关系
        for user in all_user:
            if p in user.collectionPost.all():
                user.collectionPost.remove(p)
            else:
                pass
        db.session.delete(p)
        db.session.commit()
        flash(u'帖子及其评论删除成功')
    return redirect(url_for('trade.trade_list'))

app/templates/trade/base_trade.html
{%-extends "./base.html" %}
{% import "./_macros.html" as macros %}
{% block title %}淘二手{% endblock %}
{%-block nav %}
<style>
body {
    padding-top: 140px;
}
</style>
{{ macros.subnav(logo_src='http://o8evkf73q.bkt.clouddn.com/image/JXNU_s_market.png',search_src="/query_post/",sub_attr=[("全部",url_for('trade.trade_list')),("生活用品",url_for('trade.post_category',posttag=0)),("数码科技",url_for('trade.post_category',posttag=1)),("服饰箱包",url_for('trade.post_category',posttag=2)),("图书影音",url_for('trade.post_category',posttag=3)),("其他",url_for('trade.post_category',posttag=4))])}}
{% endblock %}

{% block script %}
{% import "./_js_macros.html" as jsnode %}
{{ jsnode.navJsNode() }}
{% endblock %}

app/templates/trade/moderate.html
{%-extends "trade/base_trade.html" %}
{% import "./_macros.html" as macros %}


{% block content %}
<div class="page-header">
    <h1>评论管理</h1>
</div>
{% set moderate = True %}
{% include './_comments_moderate.html' %}
{% if pagination %}
<div class="pagination">
    {{ macros.pagination_widget(pagination, '.moderate') }}
</div>
{% endif %}
{% endblock %}

app/templates/trade/post_delete.html
{%-extends "base.html" %}
{% block content %}
    <form action="post_delete" method="post" style="padding-top: 100px;">
        <div class="input-group case-in">
            {{form.hidden_tag()}}
            <span class="glyphicon glyphicon-user"></span>
            {{ form.pid(class="input",**{"placeholder":"帖子id","require":"true"}) }}
        </div>
        {{ form.submit(class="case-in button center-block ui-form-style") }}
    </form>

{% endblock %}

app/templates/trade/query_posts.html
{%-extends "trade/trade_list.html" %}
{% block title %}{{problem}}的查询结果{% endblock %}
{% block trade_tip%}
<div style="color:#A9AA93;margin-left: 45px;"><span style="color:#FF7C6A;">{{problem}}</span>的搜索结果:</div>       
{% endblock %}

app/templates/trade/trade_detail.html
{%-extends "trade/base_trade.html" %}
{% import "./_macros.html" as macros %}
{% block title %}{{ post.goodName }}{% endblock %}
{% block content %}
<!--<nav class="ui-trade-detail-nav">
    <a href="#detail">
        <div class="ui-trade-detail-panel-label"><span class="glyphicon glyphicon-file" style="color:#fff;"> 介绍</span></div>
    </a>
    <a href="#photo">
    <div class="ui-trade-detail-panel-label"><span class="glyphicon glyphicon-camera" style="color:#fff;"> 照片</span></div>
        </a>
    <a href="#comment">
    <div class="ui-trade-detail-panel-label"><span class="glyphicon glyphicon-comment" style="color:#fff;"> 评论</span></div>
        </a>
</nav>-->
<div class="cantain-fluid">
    <div class="ui-mainct">
        <div class="ui-panel">
            <div class="ui-panel-cover" style="background:#9BB7B4">
            </div>
            <div class="row">
                <!--左边-->
                <div class="col-xs-8 left-panel">
                    <div class="row">
                        <div class="col-xs-8">
                            <div id="detail" class="ui-trade-detail-title">
                            <h1>{{ post.goodName }}</h1>
                            <h5><span class="glyphicon glyphicon-time"></span>{{post.timestamp | utcChangeToCst }}</h5>
                            <span>
                            {% if current_user.is_authenticated %}
                            {% if current_user.is_collecting(post) %}
                                <a href="{{ url_for('.uncollect',pid=post.id) }}" class="btn btn-default" role="button">取消收藏</a> 
                                {% else %}
                                <a href="{{ url_for('.collect',pid=post.id) }}" class="btn btn-default" role="button">收藏帖子</a>
                                {% endif %}
                            {% endif %}
                            </span>
                            <div class="share bdsharebuttonbox" data-tag="post">
                                <a href="#" class="fa fa-qq" data-cmd="qzone" title="分享到QQ空间"></a>
                                <a href="#" class="fa fa-weibo" data-cmd="tsina" title="分享到新浪微博"></a>
                                <a href="#" class="fa fa-wechat" data-cmd="weixin" title="分享到微信"></a>
                            </div>
                            </div>
                            
                        </div>
                        <div class="col-xs-4">
                            <div class="ui-trade-detail-price">¥{{ post.goodPrice }}</div>
                        </div>
                    </div>

                    <div  class="ui-trade-detail-content">
                        <p>{{post.body}}
                        </p>
                    </div>
                    <div id="photo" class="ui-trade-detail-content">
                        
                        
                        
                    </div>
                    <div id="comment" class="ui-trade-detail-content">
                        <div class="ui-trade-detail-comment-input">
                            <form action="/trade_detail/{{ post.id }}" method="post">
                            {{ form.hidden_tag()}}
                            {{ form.body(class="body") }}
                            
                            <div class="bottom-bg">{{ form.submit(class="bottom case-in") }}</div>
                        </form>
                        </div>
                        


                        {% include './_comments.html' %}
                        

                        <!-- <div class="ui-trade-detail-comment">
                            <div class="row">
                                <div class="col-xs-2">
                                    <div class="ui-trade-detail-comment-headbg" style="background-image:url(static/images/1.jpg)"></div>
                                </div>
                                <div class="col-xs-8">
                                    <div class="row">
                                        <div class="ui-trade-detail-comment-extendtext">can1</div>
                                        <div class="ui-trade-detail-comment-textcontain">
                                            <p>是不是傻了啊？是不是傻了啊？是不是傻了啊？是不是傻了啊？是不是傻了啊？ 是不是傻了啊？是不是傻了啊？是不是傻了啊？是不是傻了啊？是不是傻了啊？是不是傻了啊？是不是傻了啊？是不是傻了啊？是不是傻了啊？是不是傻了啊？ 是不是傻了啊？是不是傻了啊？是不是傻了啊？是不是傻了啊？是不是傻了啊？ 是不是傻了啊？是不是傻了啊？是不是傻了啊？是不是傻了啊？是不是傻了啊？
                                            </p>
                                        </div>
                                        <span class="ui-trade-detail-comment-extendtext">2016/3/3<a href="#" style="margin-left:30px;">回复</a></span>
                                    </div>

                                    <div class="row" style="margin-top:10px;margin-bottom:10px;">
                                        <div class="col-xs-2">
                                            <div class="ui-trade-detail-comment-headbg" style="background-image:url(static/images/1.jpg)"></div>
                                        </div>
                                        <div class="row">
                                            <div class="col-xs-8">
                                                <div class="ui-trade-detail-comment-extendtext">can2</div>
                                                <div class="ui-trade-detail-comment-textcontain">
                                                    <p>一脸蒙逼</p>
                                                </div>
                                                <span class="ui-trade-detail-comment-extendtext">2016/3/3<a href="#" style="margin-left:30px;">回复</a></span>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row" style="margin-top:10px;margin-bottom:10px;">
                                        <div class="col-xs-2">
                                            <div class="ui-trade-detail-comment-headbg" style="background-image:url(static/images/1.jpg)"></div>
                                        </div>
                                        <div class="row">
                                            <div class="col-xs-8">
                                                <div class="ui-trade-detail-comment-extendtext">can3</div>
                                                <div class="ui-trade-detail-comment-textcontain">
                                                    <p>@can2 一脸蒙逼</p>
                                                </div>
                                                <span class="ui-trade-detail-comment-extendtext">2016/3/3<a href="#" style="margin-left:30px;">回复</a></span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="ui-trade-detail-comment">
                            <div class="row">
                                <div class="col-xs-2">
                                    <div class="ui-trade-detail-comment-headbg" style="background-image:url(static/images/1.jpg)"></div>
                                </div>
                                <div class="col-xs-8">
                                    <div class="row">
                                        <div class="ui-trade-detail-comment-extendtext">can4</div>
                                        <div class="ui-trade-detail-comment-textcontain">
                                            <p>是不是傻了啊？是不是傻了啊？是不是傻了啊？是不是傻了啊？是不是傻了啊？ 是不是傻了啊？是不是傻了啊？是不是傻了啊？是不是傻了啊？是不是傻了啊？是不是傻了啊？是不是傻了啊？是不是傻了啊？是不是傻了啊？是不是傻了啊？ 是不是傻了啊？是不是傻了啊？是不是傻了啊？是不是傻了啊？是不是傻了啊？ 是不是傻了啊？是不是傻了啊？是不是傻了啊？是不是傻了啊？是不是傻了啊？
                                            </p>
                                        </div>
                                        <span class="ui-trade-detail-comment-extendtext">2016/3/3<a href="#" style="margin-left:30px;">回复</a></span>
                                    </div>

                                    <div class="row" style="margin-top:10px;margin-bottom:10px;">
                                        <div class="col-xs-2">
                                            <div class="ui-trade-detail-comment-headbg" style="background-image:url(static/images/1.jpg)"></div>
                                        </div>
                                        <div class="row">
                                            <div class="col-xs-8">
                                                <div class="ui-trade-detail-comment-extendtext">can5</div>
                                                <div class="ui-trade-detail-comment-textcontain">
                                                    <p>一脸蒙逼</p>
                                                </div>
                                                <span class="ui-trade-detail-comment-extendtext">2016/3/3<a href="#" style="margin-left:30px;">回复</a></span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!--end-->
                    </div>
                </div>
                <!--右边-->
                <div class="col-xs-4 right-panel">
                    <a href="{{ url_for('main.user_zone',username=post.author.userName) }}"><div class="ui-trade-detail-headbg" style="background-image:url({{ post.author.avatar}})">
                    </div>
                    </a>
                        <div class="ui-trade-detail-userinfo">
                            <h3><a href="{{ url_for('main.user_zone',username=post.author.userName) }}">{{ post.author.name }}</a> </h3>
                            <h5 class="sign">{{ post.author.id | judgeAboutmeEmpty }}</h5></div>
                    
                    <div class="ui-trade-detail-info">
                        {%if post.goodNum%}
                        <div class="info-row"><span class="glyphicon glyphicon-tags"></span>  数量:{{post.goodNum}}</div>
                        {% endif %}
                        {% if post.goodQuality %}<div class="info-row"><span class="glyphicon glyphicon-gift"></span>  {{post.goodQuality}}</div>
                        {% endif %}
                        {%if post.contact%}
                        <div class="info-row"><span class=" glyphicon glyphicon-phone"></span>  {{post.contact}}</div>
                        {% endif %}
                        {%if post.goodLocation%}
                        <div class="info-row"><span class=" glyphicon glyphicon-map-marker"></span> {{post.goodLocation}}</div>
                        {% endif %}
                        {%if post.goodBuyTime%}
                        <div class="info-row"><span class="glyphicon glyphicon-time"></span>  购买时间:{{post.goodBuyTime}}</div>
                        {% endif %}
                    </div>
                    <div class="stickypannel " >
                        <div class="ui-trade-detail-rightlist">
                            
                            <span>该用户发表过的帖子</span>
                            <ul>
                            {%  if post.author.posts %}
                            {% for userpost in post.author.posts %}
                            <li><a href="{{ url_for('trade.trade_detail',goodId=userpost.id)}}"> {{ userpost.goodName }}</a></li>
                            {%  endfor %}
                            {% else %}
                            <li>该用户还未发表过帖子~</li>
                            {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
{% endblock %} {% block script %}
<script>
$("#photo").append(function(){
        var html="";
        var imgs = ("{{post.photos}}").split(":");
        for(n in imgs){
            html+="<img src='http://7xrkww.com1.z0.glb.clouddn.com/"+imgs[n]+"' >";
        }
        return html;
    });
$(document).ready(function(){
    var ui = new UI();
    ui.sticky({
        offsetY:175,
        contain:$('.right-panel'),
    })
})
$("img").ready(function(){
    $(".right-panel").height($(".left-panel").innerHeight());
})
</script>
{{ super() }}
{% endblock %}

app/templates/trade/trade_list.html
{%-extends "trade/base_trade.html" %}
{% import "./_macros.html" as macros %}
{% block title %}淘二手{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="ui-mainct">
        
            {% block trade_tip%}{#--查询模版的提示--#}
                {% endblock %}
                {% if posts %} 
            <div id="waterfall-container" class="ui-trade-show">
                <span id="waterFallColumn_1"></span>
                <span id="waterFallColumn_2"></span>
                <span id="waterFallColumn_3"></span>
                <span id="waterFallColumn_4"></span>
                {#{ macros.listblock(posts)}#}
            </div>
            {% else %}
            <div class="ui-trade-error">:)<br>然而什么都没有</div>
            {% endif %}
        
    </div>
</div>
</div>
<!--这里是引用分页导航的局部模板macros-->
<div class="ui-pagination center-align">
    {{ macros.pagination_widget(pagination,'.trade_list')}}
</div>
</div>
{% endblock %}
{% block script %}
{{ super() }}
{% import "./_js_macros.html" as jsnode %}
{{ jsnode.colListJsNode(posts) }}

{% endblock %}

app/templates/trade/trade_post.html
{%-extends "trade/base_trade.html" %}
{% import "./_macros.html" as macros %}
{% block title %}发布二手{% endblock %}
{% block content %}
<div class="cantain-fluid">
    <div class="ui-mainct">
        <div class="ui-panel">
            <div class="ui-panel-cover" style="background:#9BB7B4;"></div>
            <div style="padding:60px 60px 0 60px;position:relative;top:-155px;">
                <div class="row">
                    <div class="ui-post-title col-sm-12">
                        发布闲置
                    </div>
                </div>
                <form action="trade_post" method="POST">
                    <div class="row ui-post-row" style="margin-top:30px;">
                        <div class="col-sm-3">
                            <span class="glyphicon glyphicon-th-list"></span> 
                            {{form.hidden_tag()}}
                            {{ form.tag()}}
                        </div>
                        <div class="col-sm-9">
                            {{ form.name(class="ui-form-style ui-post-input",**{"placeholder":"给你要卖的东西起个标题吧","required":"","maxlength":15})}}
                        </div>
                    </div>
                    <div class="row ui-post-row">
                        <div class="col-sm-8">
                            {{ form.price(class="ui-form-style ui-post-input",**{"placeholder":"出售的价格","required":""})}}
                        </div>
                        <div class="col-sm-4 tips">*价格必填</div>
                    </div>
                    <div class="row ui-post-row">
                        <div class="col-sm-8">
                            {{ form.num(class="ui-form-style ui-post-input",**{"placeholder":"数量","required":""})}}
                        </div>
                        <div class="col-sm-4 tips">出售物品的数量，必填</div>
                    </div>
                    <div class="row ui-post-row">
                        <div class="col-sm-8">
                            {{ form.location(class="ui-form-style ui-post-input",**{"placeholder":"坐标","required":""})}}
                        </div>
                        <div class="col-sm-4 tips">寝室（地址）位置，必填</div>
                    </div>
                    <div class="row ui-post-row">
                        <div class="col-sm-8">
                            {{ form.buyTime(class="ui-form-style ui-post-input",**{"placeholder":"购买时间","required":""})}}
                        </div>
                        <div class="col-sm-4 tips">
                            购买时的时间，必填</div>
                    </div>
                    <div class="row ui-post-row">
                        <div class="col-sm-8">
                            {{ form.quality(class="ui-form-style ui-post-input",**{"placeholder":"成色","required":""})}}
                        </div>
                        <div class="col-sm-4 tips">
                            物品的新旧程度，必填</div>
                    </div>
                    <div class="row ui-post-row">
                        <div class="col-sm-8">
                            {{ form.mycontact(class="ui-form-style ui-post-input",**{"placeholder":"联系方式","required":""})}}
                        </div>
                        <div class="col-sm-4 tips">
                            *联系方式，必填</div>
                    </div>
                    <div class="row ui-post-row">
                        {{ form.body(class="ui-form-style ui-post-input",**{"placeholder":"商品描述","required":""})}} 
                        {{ form.img(style="display:none;",class="imgjson") }}
                    </div>
                    <div class="row ui-post-row" data-ariapannel="uploadaira">
                        <div class="col-sm-3">
                            <div id="upload-aira" class="ui-post-upload">
                                <a id="pickfiles" href="#">
                                    <div class="btn case-in">
                                        点击这里
                                        <br>上传图片
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="row ui-post-row" style="color:#eee;">
                        *最多上传十张图片～至少需要一张照片
                    </div>
                    <div class="row ui-post-row">
                        {{form.submit(class="btn ui-post-bottom center-block case-in")}}
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %} {% block script %}
<!--依赖插件-->
<script type="text/javascript" src={{url_for( 'main.staticfile',filename='js/plupload/plupload.full.min.js' )}}></script>
<script type="text/javascript" src={{url_for( 'main.staticfile',filename='js/qinniu/dist/qiniu.min.js' )}}></script>
<!--配置-->
<script type="text/javascript" src={{url_for( 'main.staticfile',filename='js/qinniu/config.js' )}}></script>
<script type="text/javascript" src={{url_for( 'main.staticfile',filename='js/ui/Fileload.js' )}}></script>
<script type="text/javascript">
$(document).ready(function() {
    Qiniu.uploader(uploaderoption)
})
</script>
{% import "./_js_macros.html" as jsnode %}
{{ jsnode.formValidate()}}
{{ super() }}
{% endblock %}